import type { NextPage } from "next";
import Head from "next/head";
import { FormEvent, useState } from "react";
import { io } from "socket.io-client";
import { IoSend } from "react-icons/io5";
import Message from "../components/Message";

import MessageT from "../typings/MessageT";

const socket = io("http://localhost:4040");

const Home: NextPage = () => {
  const [message, setMessage] = useState("");
	const [messages, setMessages] = useState<MessageT[]>([]);

	socket.off('get-message').on("get-message", (message) => {		
    setMessages((currList) => [...currList, message]);
  });

  const sendMessage = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const messageData = {
      text: message,
      mine: Math.random() < 0.5,
		};
    socket.emit("send-message", messageData);
    setMessages((currList) => [...currList, messageData]);
    setMessage("");
  };

  return (
    <>
      <Head>
        <title>Chattr</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/chat.png" />
      </Head>

      <main className="mx-10 flex h-screen flex-col justify-between">
        <section className="my-4 overflow-y-scroll px-4 flex-1">
          {messages.map((msg, idx) => {
            return <Message key={idx} text={msg.text} mine={msg.mine} />;
          })}
        </section>
        <hr />
        <section className="m-auto my-4 w-1/2">
          <form onSubmit={sendMessage}>
            <div className="flex items-center justify-between gap-2 rounded-full bg-slate-200 py-2 px-4">
              <input
                className="w-full bg-inherit"
                placeholder="Aa"
                type="text"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
              />
              <button className="text-xl text-[#392fc6]" type="submit">
                <IoSend />
              </button>
            </div>
          </form>
        </section>
      </main>
    </>
  );
};

export default Home;
