import type { NextPage } from 'next';
import Head from 'next/head';
import { FormEvent, useState } from 'react';
import { io } from 'socket.io-client';
import { IoSend } from 'react-icons/io5';
import Message from '../components/Message';

import MessageT from '../typings/MessageT';

const socket = io('http://localhost:4040');
const myID = Math.floor(Math.random() * 999999999999999);

const Home: NextPage = () => {
	const [message, setMessage] = useState('');
	const [messages, setMessages] = useState<MessageT[]>([]);

	socket.off('get-message').on('get-message', (message) => {
		setMessages((currList) => [...currList, message]);
	});

	const sendMessage = (e: FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		const messageData = {
			text: message,
			userID: myID,
			timestamp:
				new Date(Date.now()).getHours() +
				':' +
				new Date(Date.now()).getMinutes(),
		};
		socket.emit('send-message', messageData);
		setMessages((currList) => [...currList, messageData]);
		setMessage('');
	};

	return (
		<>
			<Head>
				<title>Chattr</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/chat.png" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap"
					rel="stylesheet"
				/>
			</Head>

			<main className="mx-10 flex h-screen flex-col justify-between">
				<section className="my-4 flex-1 overflow-y-scroll px-4">
					{messages.map((msg, idx) => {
						return <Message key={idx} msg={msg} myID={myID} />;
					})}
				</section>
				<hr />
				<section className="m-auto my-4 w-1/2">
					<form onSubmit={sendMessage}>
						<div className="flex items-center justify-between gap-2 rounded-full bg-slate-200 py-2 px-4">
							<input
								className="w-full bg-inherit"
								placeholder="Aa"
								type="text"
								value={message}
								onChange={(e) => setMessage(e.target.value)}
							/>
							<button className="text-xl text-[#392fc6]" type="submit">
								<IoSend />
							</button>
						</div>
					</form>
				</section>
			</main>
		</>
	);
};

export default Home;
